### PR TITLE
Revised original 2 years old version by lanwen, set of current changes:

### PR DESCRIPTION
**Pull request by archenroot**
1. While working on SFTP connection pool I realized some old bug due to grep4j dependency on lombok-0.11.6 in Netbeans, some details available here - https://github.com/rzwitserloot/lombok/issues/626
2. While updating lombok dependency I updated all of the dependency libraries to:
   - commons-io-2.4.jar
   - commons-lang-2.6.jar
   - commons-lang3-3.4.jar
   - commons-pool-1.6.jar
   - guava-19.0.rc2.jar
   - jsch-0.1.53.jar
   - jsr305-2.0.1.jar - new
   - lambdaj-2.3.3.jar
   - lombok-1.16.6.jar
   - cglib-nodep-2.2.jar
   - hamcrest-all-1.1.jar
   - objenesis-1.1.jar
3. I have found some bug relevant to Test cases especially done on Windows, so will update them, for now build with `mvn -Dmaven.test.skip=true install` for now.
4. Source code is now targeted to Java 1.7 version.

### CODE REVIEW

**Comment by lanwen** [comment]
wow, its just a fork of https://code.google.com/p/grep4j/ to not miss this project :)

maybe you should find original author and request him to officially migrate to GH. 

but thanks for update!

**Comment by archenroot** [comment]
Anyway the code.google became read only and there is no other fork, so let's wait for Marco's (original owner) answer.

**Comment by archenroot** [comment]
Ok, I found original author and his co-worker so he migrated to github and
I will be working on his original branch:

The plan with grep4j from my perspective is basically to keep it up-to-date:
Step 1. ) update libraries and compile with test on both Windows (Windows
10) and Linux(Gentoo)  against Oracle JDK 1.7.0_79
Step 2.) release in maven/github
Step 3.) Prepare list of possible improvements with respect to Oracle JDK
1.8 (latest stable) and do transition of the code
Step 4.) release in maven/github

That's it. So new original Marco's repository is here:
https://github.com/marcocast/grep4j

Ladislav

2015-10-20 10:35 GMT+01:00 Merkushev Kirill notifications@github.com:

**Comment by lanwen** [comment]
@archenroot thanks!

**Pull request merged**
